# Generated by Django 5.2.6 on 2025-09-11 02:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_caracteristica', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=50, unique=True)),
                ('titulo_publicacion', models.CharField(max_length=255)),
                ('descripcion_publica', models.TextField(blank=True, null=True)),
                ('direccion_exacta', models.CharField(max_length=255)),
                ('precio_referencial', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BS', 'BS')], default='USD', max_length=3)),
                ('superficie_terreno', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_construccion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.IntegerField(default=0)),
                ('banos', models.IntegerField(default=0)),
                ('puestos_estacionamiento', models.IntegerField(default=0)),
                ('ano_construccion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('estatus_venta', models.CharField(choices=[('Disponible', 'Disponible'), ('Vendido', 'Vendido'), ('Alquilado', 'Alquilado'), ('Reservado', 'Reservado')], default='Disponible', max_length=10)),
                ('estatus_moderacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=10)),
                ('fecha_moderacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_ciudad', models.CharField(max_length=100)),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades', to='api.estado')),
            ],
            options={
                'unique_together': {('nombre_ciudad', 'estado')},
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='api.inmueble')),
            ],
        ),
        migrations.CreateModel(
            name='InmuebleCaracteristica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255, null=True)),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caracteristica')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inmueble')),
            ],
            options={
                'unique_together': {('inmueble', 'caracteristica')},
            },
        ),
        migrations.AddField(
            model_name='inmueble',
            name='caracteristicas',
            field=models.ManyToManyField(related_name='inmuebles', through='api.InmuebleCaracteristica', to='api.caracteristica'),
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_municipio', models.CharField(max_length=150)),
                ('ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipios', to='api.ciudad')),
            ],
            options={
                'unique_together': {('nombre_municipio', 'ciudad')},
            },
        ),
        migrations.AddField(
            model_name='inmueble',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='api.municipio'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inmuebles', to='api.tipoinmueble'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cedula', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('rif', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='api.rol')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('Venta', 'Venta'), ('Alquiler', 'Alquiler')], max_length=10)),
                ('fecha_operacion', models.DateField()),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=18)),
                ('moneda_cierre', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('BS', 'BS')], default='USD', max_length=3)),
                ('notas', models.TextField(blank=True, null=True)),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operaciones', to='api.inmueble')),
                ('usuario_comprador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='api.usuario')),
                ('usuario_vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido_mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='api.conversacion')),
                ('usuario_emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to='api.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='inmueble',
            name='moderador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_inmuebles', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='usuario_interesado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_interesado', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='usuario_vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_vendedor', to='api.usuario'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_cita', models.DateTimeField()),
                ('estatus_cita', models.CharField(choices=[('Programada', 'Programada'), ('Completada', 'Completada'), ('Cancelada', 'Cancelada')], default='Programada', max_length=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('inmueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='api.inmueble')),
                ('usuario_interesado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_interesado', to='api.usuario')),
                ('usuario_propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_propietario', to='api.usuario')),
            ],
        ),
        migrations.AddConstraint(
            model_name='conversacion',
            constraint=models.UniqueConstraint(fields=('inmueble', 'usuario_interesado', 'usuario_vendedor'), name='unique_conversacion_por_inmueble_y_usuarios'),
        ),
    ]
